// <auto-generated />
using System;
using BackendTest.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTest.Infrastructure.Migrations
{
    [DbContext(typeof(BackendTestDbContext))]
    [Migration("20260716003625_SeedTestData")]
    partial class SeedTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BackendTest.Infrastructure.Models.PersonPersistenceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("YearOfBirth")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("BackendTest.Infrastructure.Models.ProductPersistenceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BackendTest.Infrastructure.Models.PurchasePersistenceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("ProductPersistenceModelPurchasePersistenceModel", b =>
                {
                    b.Property<long>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PurchasePersistenceModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductsId", "PurchasePersistenceModelId");

                    b.HasIndex("PurchasePersistenceModelId");

                    b.ToTable("purchase_products", (string)null);
                });

            modelBuilder.Entity("BackendTest.Infrastructure.Models.PurchasePersistenceModel", b =>
                {
                    b.HasOne("BackendTest.Infrastructure.Models.PersonPersistenceModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProductPersistenceModelPurchasePersistenceModel", b =>
                {
                    b.HasOne("BackendTest.Infrastructure.Models.ProductPersistenceModel", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTest.Infrastructure.Models.PurchasePersistenceModel", null)
                        .WithMany()
                        .HasForeignKey("PurchasePersistenceModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
